[package]
name = "adsabs"
version = "0.0.0-dev.0"
authors = ["Dan Foreman-Mackey <foreman.mackey@gmail.com>"]
edition = "2018"
readme = "README.md"
homepage = "https://github.com/dfm/adsabs"
repository = "https://github.com/dfm/adsabs.git"
description = "A client for the SAO/NASA Astrophysics Data System API"
license = "Apache-2.0"
documentation = "https://docs.rs/adsabs"
categories = ["science", "api-bindings"]
exclude = ["/.github/"]

[dependencies]
reqwest = "0.11.6"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
chrono = { version = "0.4.19", features = ["serde"] }
dirs = "4.0.0"
url = "2.2.2"

[dev-dependencies]
tokio = { version = "1.12.0", features = ["full"] }

[[example]]
name = "basic"
path = "examples/basic.rs"
